name: petplus
description: A Flutter project exemplifying how to build a customer service messaging app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  json_annotation: ^4.8.0
  provider: ^6.0.3
  equatable: ^2.0.5
  get_it: ^7.2.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  shared_preferences: ^2.0.15
  pusher_channels_flutter: ^2.1.0
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  intl: ^0.17.0
#  pusher_beams: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  image_path: 'assets/images/icon_app.png'
  android: true
  ios: true
  adaptive_icon_background: '#ffffff'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
